//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CashDisbursement
    {
        private JEVEGA_UsDbEntities dbUSClinic = new JEVEGA_UsDbEntities();

        public int Id { get; set; }

        [Display(Name = "Item Description")]
        [Required(ErrorMessage = "*")]
        public string ItemDescription { get; set; }

        [Display(Name = "Category")]
        [Required(ErrorMessage = "*")]
        public short ItemCategory { get; set; }

        [Display(Name = "Amount")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal Amount { get; set; }

        [Display(Name = "Date")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateSpent { get; set; }

        [Display(Name = "Reference No.")]
        public string ReferenceNo { get; set; }

        [Display(Name = "Image Ref.")]
        public Nullable<bool> ItemImage { get; set; }

        public string getCategoryName
        {
            get
            {
                string category_name = dbUSClinic.ExpenseCategories.Find(ItemCategory).ExpenseCategory1.ToString();
                return category_name;
            }
        }


    }
}
