//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultingDoctor
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PostTitle { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> ProfilePic { get; set; }
        public string PRCLicenseNo { get; set; }
    }
}
