//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiagnosticExamCategory
    {
        public int Id { get; set; }
        [Display(Name = "Exam Category Name")]
        [Required(ErrorMessage = "*")]
        public string CategoryName { get; set; }
    }
}
