//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExamReportTemplate
    {
        JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();

        public int Id { get; set; }

        [Display(Name = "Report Category")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> ReportCategory { get; set; }

        [Display(Name = "Report Write-Ups")]
        [Required(ErrorMessage = "*")]
        public string ReportWriteUps { get; set; }

        [Display(Name = "Report Name")]
        [Required(ErrorMessage = "*")]
        public string ReportName { get; set; }

        public string getReportCategoryName
        {
            get
            {
                string category_name = "";

                DiagnosticExam diagExam = db.DiagnosticExams.Find(ReportCategory);
                string examName = diagExam.ExamName;
                int examCatId = (int)diagExam.ExamCategory;

                DiagnosticExamCategory diagExamCat = db.DiagnosticExamCategories.Find(examCatId);
                string examCategoryDesc = diagExamCat.CategoryName;

                category_name = examCategoryDesc + " - " + examName;
                return category_name;
            }
        } //--

    }
}
