//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sonographer
    {
        public int Id { get; set; }

        [Display(Name = "Firstname")]
        [Required(ErrorMessage = "*")]
        public string FirstName { get; set; }

        [Display(Name = "Lastname")]
        [Required(ErrorMessage = "*")]
        public string LastName { get; set; }

        [Display(Name = "Job Title")]
        [Required(ErrorMessage = "*")]
        public string PostTitle { get; set; }

        [Display(Name = "Email")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "*invalid E-mail ...")]
        public string Email { get; set; }

        [Display(Name = "Phone")]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "*invalid phone no. ...")]
        public string Phone { get; set; }

        [Display(Name = "Profile Picture")]
        public Nullable<bool> ProfilePic { get; set; }

        [Display(Name = "PRC License No.")]
        public string PrcLicenseNo { get; set; }

        public string GetFullname
        {
            get { return LastName + ", " + FirstName; }
        }
    }
}
