//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEVEGA_Us_Cliniic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JEVEGA_USDB_Entities : DbContext
    {
        public JEVEGA_USDB_Entities()
            : base("name=JEVEGA_USDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiagnosticExam> DiagnosticExams { get; set; }
        public virtual DbSet<DiagnosticExamCategory> DiagnosticExamCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PatientData> PatientDatas { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<RadiologistDoctor> RadiologistDoctors { get; set; }
        public virtual DbSet<Sonographer> Sonographers { get; set; }
        public virtual DbSet<PatientExam> PatientExams { get; set; }
    }
}
